[package]
name = "btc_older_test"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { version="1.0.0", features = ["file_store"] }
bdk_esplora = { version = "0.20", features = ["blocking"] }
anyhow = "1"


